### ISSUE TITLE
Omitting 'redis' key in config.yml gives Undefined index: redis error

### ISSUE THREAD

**Issue by yubinchen18** [mariusbalcytis/gentle-force-bundle#5]
Omitting 'redis' key in config.yml gives

```
(1/1) ContextErrorException
Notice: Undefined index: redis
```

so you can't configure the bundle without using a redis caching service?

**Comment by mariusbalcytis** [comment]
Redis is a strict requirement at the moment as locking mechanism and all the counters are stored in there.

There's an [open issue](https://github.com/mariusbalcytis/gentle-force/issues/1) in library repository, but I don't know if someone would really use any of other integrations.

In bundle configuration that key should be made required so that developer would have nicer error message.
